web/router.ex
defmodule PhMicroblog.Router do
  use PhMicroblog.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers

    plug PhMicroblog.CurrentUser
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug PhMicroblog.CurrentUser, mode: :json
  end

  scope "/", PhMicroblog do
    pipe_through :browser # Use the default browser stack

    get "/",                     StaticPageController, :home
    get "/static_pages/help",    StaticPageController, :help
    get "/static_pages/about",   StaticPageController, :about
    get "/static_pages/contact", StaticPageController, :contact

    get "/signup", UserController, :new

    resources "/users", UserController, except: [:new] do
      get "/following", UserController, :following, as: :relationship
      get "/followers", UserController, :followers, as: :relationship
    end

    get    "/login",  SessionController, :new
    post   "/login",  SessionController, :create
    delete "/logout", SessionController, :destroy

    resources "/microposts", MicropostController, only: [:create, :delete]
    resources "/relationships", RelationshipController, only: [:create, :delete]
  end

  scope "/api", PhMicroblog.Json, as: :api do
    pipe_through :api

    post "/login",  SessionController, :create

    resources "/users", UserController, except: [:new, :edit]
    resources "/microposts", MicropostController, only: [:create, :delete]

    get "/feed", UserController, :feed, as: :feed
  end
end

web/models/user.ex
defmodule PhMicroblog.User do
  use PhMicroblog.Web, :model

  import Ecto.Query
  alias PhMicroblog.{Micropost, Relationship, Repo}

  schema "users" do
    field :name, :string
    field :email, :string
    field :password_digest, :string
    field :admin, :boolean, default: false

    field :password, :string, virtual: true

    has_many :microposts, Micropost, on_delete: :delete_all

    has_many :active_relationships, Relationship,
      foreign_key: :follower_id,
      on_delete: :delete_all
    has_many :following, through: [:active_relationships, :followed]

    has_many :passive_relationships, Relationship,
      foreign_key: :followed_id,
      on_delete: :delete_all
    has_many :followers, through: [:passive_relationships, :follower]

    timestamps
  end

  @allowed ~w[name email password]

  @email_format ~r/\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  def changeset(model, params \\ %{}) do
    model
    |> cast(params, @allowed)
    |> generate_digest
    |> validate_required(:name)
    |> validate_required(:email)
    |> validate_required(:password_digest)
    |> validate_length(:name, max: 50)
    |> validate_length(:email, max: 255)
    |> validate_length(:password, min: 6)
    |> validate_format(:email, @email_format)
    |> validate_confirmation(:password)
    |> update_change(:email, &downcase_email/1)
    |> unique_constraint(:email)
  end

  def authenticate(nil, _password) do
    Comeonin.Bcrypt.dummy_checkpw()
  end

  def authenticate(user, password) do
    if Comeonin.Bcrypt.checkpw(password, user.password_digest) do
      {:ok, user}
    else
      :error
    end
  end

  def feed(user) do
    following_ids = user |> assoc(:following) |> Repo.all |> Enum.map(& &1.id)
    targets = [user.id | following_ids]

    Micropost
    |> where([m], m.user_id in ^targets)
    |> preload([m], :user)
    |> order_by([m], desc: m.inserted_at)
  end

  def following?(user, other) do
    user |> assoc(:following) |> Repo.get(other.id) != nil
  end

  def following_count(user) do
    user
    |> assoc(:following)
    |> select([f], count(f.id))
    |> Repo.one
  end

  def followers_count(user) do
    user
    |> assoc(:followers)
    |> select([f], count(f.id))
    |> Repo.one
  end

  defp generate_digest(changeset) do
    password = get_field(changeset, :password, nil)
    if password != nil do
      put_change(changeset, :password_digest, Comeonin.Bcrypt.hashpwsalt(password))
    else
      changeset
    end
  end

  defp downcase_email(nil),   do: nil
  defp downcase_email(email), do: String.downcase(email)
end

web/controllers/json/user_controller.ex
defmodule PhMicroblog.Json.UserController do
  use PhMicroblog.Web, :json_controller

  alias PhMicroblog.{User, Repo, Pager}
  alias PhMicroblog.{RequireLogin, CorrectUser}
  alias PhMicroblog.Json.{MicropostView, ChangesetView, ErrorView}

  plug RequireLogin, [mode: :json] when action in [:index, :update, :delete, :feed]
  plug :scrub_params, "user" when action in [:create, :update]
  plug :set_user when action in [:show, :update, :delete]
  plug CorrectUser, [accessor: [:user], mode: :json] when action in [:update]
  plug :admin_only when action in [:delete]

  def index(conn, params) do
    page = User |> Pager.paginate(page_number: params["p"])

    render(conn, page: page)
  end

  def show(conn, _params) do
    render(conn)
  end

  def create(conn, %{"user" => user_params}) do
    changeset = User.changeset(%User{}, user_params)

    case Repo.insert(changeset) do
      {:ok, user} ->
        conn
        |> put_status(201)
        |> render("show.json", user: user)
      {:error, changeset} ->
        conn
        |> put_status(422)
        |> render(ChangesetView, "error.json", changeset: changeset)
    end
  end

  def update(conn, %{"user" => user_params}) do
    changeset = User.changeset(conn.assigns.user, user_params)

    case Repo.update(changeset) do
      {:ok, user} ->
        conn
        |> put_status(200)
        |> render("show.json", user: user)
      {:error, changeset} ->
        conn
        |> put_status(422)
        |> render(ChangesetView, "error.json", changeset: changeset)
    end
  end

  def delete(conn, _params) do
    conn.assigns.user |> Repo.delete!

    conn |> put_status(204) |> json(%{})
  end

  def feed(conn, params) do
    page = conn.assigns.current_user
      |> User.feed()
      |> Pager.paginate(page_number: params["p"])

    render(conn, MicropostView, "index.json", page: page)
  end

  defp set_user(conn, _opts) do
    user = User |> Repo.get!(conn.params["id"] || conn.params["user_id"])

    conn |> assign(:user, user)
  end

  defp admin_only(conn, _opts) do
    if conn.assigns.current_user.admin do
      conn
    else
      conn |> put_status(401) |> render(ErrorView, "401.json") |> halt
    end
  end
end

web/controllers/user_controller.ex
defmodule PhMicroblog.UserController do
  use PhMicroblog.Web, :controller

  import Ecto.Query

  alias PhMicroblog.{User, Repo, Pager}
  alias PhMicroblog.{RequireLogin, CorrectUser, CurrentUser}

  plug RequireLogin when action in [:index, :edit, :update, :delete, :following, :followers]
  plug :scrub_params, "user" when action in [:create, :update]
  plug :set_user when action in [:show, :edit, :update, :delete, :following, :followers]
  plug CorrectUser, [accessor: [:user]] when action in [:edit, :update]
  plug :admin_only when action in [:delete]

  def index(conn, params) do
    page = User |> Pager.paginate(page_number: params["p"])

    conn
    |> assign(:title, "All users")
    |> render(page: page)
  end

  def new(conn, _params) do
    changeset = User.changeset(%User{})

    conn
    |> assign(:title, "Sign up")
    |> render(changeset: changeset)
  end

  def create(conn, %{"user" => user_params}) do
    changeset = User.changeset(%User{}, user_params)

    case Repo.insert(changeset) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "Welcome to Sample App!")
        |> put_session(CurrentUser.session_key, user.id)
        |> redirect_back_or(user_path(conn, :show, user))
      {:error, changeset} ->
        render conn, "new.html", title: "Sign up", changeset: changeset
    end
  end

  def show(conn, params) do
    user = conn.assigns.user
    page = user
      |> assoc(:microposts)
      |> preload(:user)
      |> order_by([m], {:desc, :inserted_at})
      |> Pager.paginate(page_number: params["p"])

    conn
    |> assign(:title, user.name)
    |> render(user: user, page: page)
  end

  def edit(conn, _params) do
    user = conn.assigns.user
    changeset = User.changeset(user)

    conn
    |> assign(:title, "Edit user")
    |> render(user: user, changeset: changeset)
  end

  def update(conn, %{"user" => user_params}) do
    user = conn.assigns.user
    changeset = User.changeset(user, user_params)

    case Repo.update(changeset) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "Profile updated")
        |> redirect(to: user_path(conn, :show, user))
      {:error, changeset} ->
        conn
        |> assign(:title, "Edit user")
        |> render("edit.html", changeset: changeset, user: user)
    end
  end

  def delete(conn, _params) do
    Repo.delete!(conn.assigns.user)

    conn
    |> put_flash(:info, "User deleted")
    |> redirect(to: user_path(conn, :index))
  end

  def following(conn, params) do
    page = conn.assigns.user
      |> assoc(:following)
      |> Pager.paginate(page_number: params["p"])

    render conn, "show_follow.html", page: page, title: "Following"
  end

  def followers(conn, params) do
    page = conn.assigns.user
      |> assoc(:followers)
      |> Pager.paginate(page_number: params["p"])

    render conn, "show_follow.html", page: page, title: "Followers"
  end

  defp set_user(conn, _opts) do
    user = Repo.get!(User, conn.params["id"] || conn.params["user_id"])
      |> Repo.preload(:microposts)

    conn |> assign(:user, user)
  end

  defp admin_only(conn, _opts) do
    if conn.assigns.current_user.admin do
      conn
    else
      conn |> redirect(to: static_page_path(conn, :home)) |> halt
    end
  end

  defp redirect_back_or(conn, default) do
    path = RequireLogin.forwarding_path(conn) || default

    conn
    |> RequireLogin.delete_forwarding_path
    |> redirect(to: path)
  end
end

web/views/json/user_view.ex
defmodule PhMicroblog.Json.UserView do
  use PhMicroblog.Web, :view

  def render("index.json", %{page: page}) do
    %{users: render_many(page.entries, __MODULE__, "user.json")}
  end

  def render("show.json", %{user: user}) do
    %{user: render_one(user, __MODULE__, "user.json")}
  end

  def render("user.json", %{user: user}) do
    %{
      id: user.id,
      name: user.name,
      avatar_url: gravatar_url(user)
     }
  end
end

web/views/user_view.ex
defmodule PhMicroblog.UserView do
  use PhMicroblog.Web, :view
end

web/templates/user/edit.html.eex
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @changeset, user_path(@conn, :update, @user.id), fn f -> %>
      <%= render "form.html", f: f %>

      <%= submit "Save changes", class: "btn btn-primary" %>
    <% end %>

    <div class="gravatar_edit">
      <%= tag :img, src: gravatar_url(@user) %>
      <a href="http://gravatar.com/emails" target="_blank">change</a>
    </div>
  </div>
</div>

web/templates/user/follow.html.eex
<%= form_for @conn, relationship_path(@conn, :create), [as: :relationship], fn f -> %>
  <div><%= hidden_input f, :followed_id, value: @user.id %></div>
  <%= submit "Follow", class: "btn btn-primary" %>
<% end %>

web/templates/user/follow_form.html.eex
<%= if !current_user?(@conn, @user) do %>
  <div id="follow_form">
    <%= if PhMicroblog.User.following?(@current_user, @user) do %>
      <%= render "unfollow.html", conn: @conn, user: @user %>
    <% else %>
      <%= render "follow.html", conn: @conn, user: @user %>
    <% end %>
  </div>
<% end %>

web/templates/user/form.html.eex
<div class="form-group <%= has_error(@f, :name) %>">
  <%= label @f, :name, class: "control-label" %>
  <%= text_input @f, :name, class: "form-control" %>
  <%= error_tag @f, :name %>
</div>

<div class="form-group <%= has_error(@f, :email) %>">
  <%= label @f, :email, class: "control-label" %>
  <%= email_input @f, :email, class: "form-control" %>
  <%= error_tag @f, :email %>
</div>

<div class="form-group <%= has_error(@f, :password) %>">
  <%= label @f, :password, class: "control-label" %>
  <%= password_input @f, :password, class: "form-control" %>
  <%= error_tag @f, :password %>
</div>

<div class="form-group <%= has_error(@f, :password_confirmation) %>">
  <%= label @f, :password_confirmation, "Confirmation", class: "control-label" %>
  <%= password_input @f, :password_confirmation, class: "form-control" %>
  <%= error_tag @f, :password_confirmation %>
</div>

web/templates/user/index.html.eex
<h1>All users</h1>

<%= render SharedView, "pager.html", conn: @conn, page: @page %>

<ul class="users">
  <%= for user <- @page.entries do %>
    <li>
      <p class="pull-left">
        <%= tag :img, src: gravatar_url(user, 50) %>
        <%= link user.name, to: user_path(@conn, :show, user) %>
      </p>
      <%= if @current_user.admin && @current_user.id != user.id do %>
        <%= link "delete", to: user_path(@conn, :delete, user),
          method: :delete, data: [confirm: "You sure?"], class: "text-danger pull-right" %>
      <% end %>
    </li>
  <% end %>
</ul>

<%= render SharedView, "pager.html", conn: @conn, page: @page %>

web/templates/user/new.html.eex
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @changeset, user_path(@conn, :create), fn f -> %>
      <%= render "form.html", f: f %>

      <%= submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

web/templates/user/show.html.eex
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= tag :img, src: gravatar_url(@user) %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
  <div class="col-md-8">
    <%= if logged_in?(@conn) do %>
      <%= render "follow_form.html", conn: @conn, current_user: @current_user, user: @user %>
    <% end %>
    <%= if @page.total_entries > 0 do %>
      <h3>Microposts (<%= @page.total_entries %>)</h3>
      <%= render SharedView, "feed.html", conn: @conn, page: @page %>
    <% end %>
  </div>
</div>

web/templates/user/show_follow.html.eex
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= tag :img, src: gravatar_url(@user) %>
      <h1><%= @user.name %></h1>
      <span><%= link "view my profile", to: user_path(@conn, :show, @user) %></span>
      <span><b>Microposts:</b> <%= Enum.count @user.microposts %></span>
    </section>
    <section class="stats">
      <%= if @page.total_entries > 0 do %>
        <div class="user_avatars">
          <%= for user <- @page.entries do %>
            <%= link to: user_path(@conn, :show, user) do %>
              <%= tag :img, src: gravatar_url(user, 30) %>
            <% end %>
          <% end %>
        </div>
      <% end %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3><%= @title %></h3>
    <%= if @page.total_entries > 0 do %>
      <ul class="users follow">
        <%= for user <- @page.entries do %>
          <li>
            <p class="pull-left">
              <%= tag :img, src: gravatar_url(user, 50) %>
              <%= link user.name, to: user_path(@conn, :show, user) %>
            </p>
            <%= if @current_user.admin && @current_user.id != user.id do %>
              <%= link "delete", to: user_path(@conn, :delete, user),
                method: :delete, data: [confirm: "You sure?"], class: "text-danger pull-right" %>
            <% end %>
          </li>
        <% end %>
      </ul>
      <%= render SharedView, "pager.html", conn: @conn, page: @page %>
    <% end %>
  </div>
</div>

web/templates/user/unfollow.html.eex
<%= form_for @conn, relationship_path(@conn, :delete, @user), [as: :relationship, method: :delete], fn _f -> %>
  <%= submit "Unfollow", class: "btn" %>
<% end %>