web/router.ex
defmodule PhMicroblog.Router do
  use PhMicroblog.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers

    plug PhMicroblog.CurrentUser
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug PhMicroblog.CurrentUser, mode: :json
  end

  scope "/", PhMicroblog do
    pipe_through :browser # Use the default browser stack

    get "/",                     StaticPageController, :home
    get "/static_pages/help",    StaticPageController, :help
    get "/static_pages/about",   StaticPageController, :about
    get "/static_pages/contact", StaticPageController, :contact

    get "/signup", UserController, :new

    resources "/users", UserController, except: [:new] do
      get "/following", UserController, :following, as: :relationship
      get "/followers", UserController, :followers, as: :relationship
    end

    get    "/login",  SessionController, :new
    post   "/login",  SessionController, :create
    delete "/logout", SessionController, :destroy

    resources "/microposts", MicropostController, only: [:create, :delete]
    resources "/relationships", RelationshipController, only: [:create, :delete]
  end

  scope "/api", PhMicroblog.Json, as: :api do
    pipe_through :api

    post "/login",  SessionController, :create

    resources "/users", UserController, except: [:new, :edit]
    resources "/microposts", MicropostController, only: [:create, :delete]

    get "/feed", UserController, :feed, as: :feed
  end
end

web/views/layout_view.ex
defmodule PhMicroblog.LayoutView do
  use PhMicroblog.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title><%= full_title @conn.assigns[:title] %></title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>

  <body>
    <%= render "header.html", conn: @conn %>

    <main role="main" class="container">
      <%= if get_flash(@conn, :info) != nil do %>
        <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <% end %>
      <%= if get_flash(@conn, :error) != nil do %>
        <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <% end %>

      <%= render @view_module, @view_template, assigns %>

      <%= render "footer.html", conn: @conn %>
    </main>

    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

web/templates/layout/footer.html.eex
<footer class="footer">
  <small>
    The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link "About",   to: static_page_path(@conn, :about) %></li>
      <li><%= link "Contact", to: static_page_path(@conn, :contact) %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

web/templates/layout/header.html.eex
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link "sample app", to: static_page_path(@conn, :home), id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link "Home",   to: static_page_path(@conn, :home) %></li>
        <li><%= link "Help",   to: static_page_path(@conn, :help) %></li>
        <%= if logged_in?(@conn) do %>
          <li><%= link "Users", to: user_path(@conn, :index) %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link "Profile", to: user_path(@conn, :show, @conn.assigns.current_user) %></li>
              <li><%= link "Settings", to: user_path(@conn, :edit, @conn.assigns.current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link "Log out", to: session_path(@conn, :destroy), method: :delete, form: [class: "logout"] %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link "Log in", to: session_path(@conn, :new) %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>