web/router.ex
defmodule PhMicroblog.Router do
  use PhMicroblog.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers

    plug PhMicroblog.CurrentUser
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug PhMicroblog.CurrentUser, mode: :json
  end

  scope "/", PhMicroblog do
    pipe_through :browser # Use the default browser stack

    get "/",                     StaticPageController, :home
    get "/static_pages/help",    StaticPageController, :help
    get "/static_pages/about",   StaticPageController, :about
    get "/static_pages/contact", StaticPageController, :contact

    get "/signup", UserController, :new

    resources "/users", UserController, except: [:new] do
      get "/following", UserController, :following, as: :relationship
      get "/followers", UserController, :followers, as: :relationship
    end

    get    "/login",  SessionController, :new
    post   "/login",  SessionController, :create
    delete "/logout", SessionController, :destroy

    resources "/microposts", MicropostController, only: [:create, :delete]
    resources "/relationships", RelationshipController, only: [:create, :delete]
  end

  scope "/api", PhMicroblog.Json, as: :api do
    pipe_through :api

    post "/login",  SessionController, :create

    resources "/users", UserController, except: [:new, :edit]
    resources "/microposts", MicropostController, only: [:create, :delete]

    get "/feed", UserController, :feed, as: :feed
  end
end

web/views/shared_view.ex
defmodule PhMicroblog.SharedView do
  use PhMicroblog.Web, :view

  alias PhMicroblog.Pager
end

web/templates/shared/feed.html.eex
<ol class="microposts">
  <%= Enum.map @page.entries, fn micropost -> %>
    <li id="micropost-<%= micropost.id %>">
      <%= link to: user_path(@conn, :show, micropost.user) do %>
        <%= tag :img, src: gravatar_url(micropost.user, 50), class: "avatar" %>
      <% end %>
      <span class="user"><%= link micropost.user.name, to: user_path(@conn, :show, micropost.user) %></span>
      <span class="content"><%= micropost.content %></span>
      <span class="timestamp">
        Posted at <%= micropost.inserted_at %>
      </span>
      <%= if current_user?(@conn, micropost.user) do %>
        <%= link "delete", to: micropost_path(@conn, :delete, micropost), method: :delete, data: [confirm: "You sure?"],
        form: [style: "display: inline;"] %>
      <% end %>
    </li>
  <% end %>
</ol>
<%= render SharedView, "pager.html", conn: @conn, page: @page %>

web/templates/shared/micropost_form.html.eex
<%= form_for @changeset, micropost_path(@conn, :create), fn f -> %>
  <div class="field form-group <%= has_error(f, :content) %>">
    <%= textarea f, :content, placeholder: "Compose new micropost...", class: "form-control" %>
    <%= error_tag f, :content %>
  </div>
  <%= submit "Post", class: "btn btn-primary" %>
<% end %>

web/templates/shared/pager.html.eex
<nav>
  <ul class="pager">
    <li class='<%= if Pager.first_page?(@page), do: "previous disabled", else: "previous" %>'>
      <%= link to: Pager.prev_page_path(@conn, @page) do %>
        <span aria-hidden="true">&larr;</span> Prev
      <% end %>
    </li>

    <li class='<%= if Pager.last_page?(@page), do: "next disabled", else: "next" %>'>
      <%= link to: Pager.next_page_path(@conn, @page) do %>
        Next <span aria-hidden="true">&rarr;</span>
      <% end %>
    </li>
  </ul>
</nav>

web/templates/shared/stats.html.eex
<div class="stats">
  <%= link to: user_relationship_path(@conn, :following, @user) do %>
    <strong id="following" class="stat">
      <%= PhMicroblog.User.following_count(@user) %>
    </strong>
    following
  <% end %>
  <%= link to: user_relationship_path(@conn, :followers, @user) do %>
    <strong id="followers" class="stat">
      <%= PhMicroblog.User.followers_count(@user) %>
    </strong>
    followers
  <% end %>
</div>

web/templates/shared/user_info.html.eex
<%= link to: user_path(@conn, :show, @user), class: "gravatar" do %>
  <%= tag :img, src: gravatar_url(@user, 50) %>
<% end %>
<h1><%= @user.name %></h1>
<span><%= link "view my profile", to: user_path(@conn, :show, @user) %></span>
<span><%= @page.total_entries %> microposts</span>